title: Mohammad Ganji
theme: jekyll-theme-minimal
logo: /image/me.jpg
excerpt_separator: "\n"

external:
  - {title: Mail, icon: envelope, url: ""}
  - {title: Github, icon: github, url: ""}
  - {title: Twitter, icon: twitter, url: ""}

